### PR TITLE
The first cut of activity log (APIm analytics) reporting

### PR DESCRIPTION
**Pull request by bajtos**
The first commit fixes a bug in `server/policy-middleware.json` where paths entered as regexp-like strings were not converted before they were sent to express. As a result, some policies were never invoked, because  a path string like "^/api/(.*)$" never matches any request URL.

The second commit implements a new policy "activityLog" that reports API events to IBM APIm backend.

Example configuration:

```
{
  "name": "default-activity-log-policy",
  "type": "activityLog",
  "phase": "initial:before",
  "connection": {
    "url": "https://myhost:9443/x2020/v1/events/_bulk",
    "auth": {
      "keyFile": "server/apim/private-key.pem",
      "certFile": "server/apim/public-cert.pem",
      "passphrase": "****",
      "rejectUnauthorized": false
    }
  },
  "orgId": "some-org-id",
  "envId": "some-env-id"
}
```

Requires https://github.com/strongloop/loopback-boot/pull/159
Connect to strongloop-internal/scrum-loopback#556

/to @raymondfeng @ritch please review

### CODE REVIEW

**Comment by bajtos** [comment]
This is my initial version how to package & configure this code in strong-gateway. I expect the configuration will change as part of refactoring strong-gateway into a standalone executable. @ritch you have a free hand to pick whatever config approach works best, I am not married to the current implementation.

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
@rmg the build is failing because Jenkins pulls jshint version 2.9.0 which is not available on npmjs yet (AFAICT). Where is this version coming from?

The error (Use the function form of "use strict") is usually reported when jshint does not pick `node:true` from the config. However, this project has `.jshintrc` with `node:true`...

Thoughts?

**Comment by ritch** [comment]
Yes keep in mind the loading of policies and middleware  is going to change drastically. The middle where phasing will probably remain exactly the same. Policy plug-in infrastructure will be totally different.  That being said it's not going to be too difficult to re-factor any existing policy into the new plug-in structure.

**Comment by bajtos** [comment]
Closing in favour of https://github.ibm.com/apimesh/strong-gateway/pull/1.

**Pull request closed without merging**
